file-save-path: E:\userImg\
file:
  location: E:\userImg\
logging:
  level:
    com.workmexh.mapper: DEBUG
server:
  port: 8089 # web服务端口号
  servlet:
    multipart:
      enabled: true # 启用文件上传
      location: # 上传文件临时保存位置
      max-file-size: 2MB # 单个文件上传最大大小限制
      max-request-size: 50MB # 单次请求主体最大大小限制
  mvc:
    format:
      date: yyyy-MM-dd # 日期格式
      date-time: yyyy-MM-dd HH:mm:ss # 日期时间格式
      time: HH:mm:ss # 时间格式
    servlet:
      path: / # servlet路径
      static-path-pattern: # 匹配静态资源路径
    view:
      prefix:  # view前缀
      suffix:  # view后缀，如：.jsp
# MyBatis配置


mybatis:
  configuration:

    #开启驼峰命名匹配映射
    map-underscore-to-camel-case: true
  #配置MyBatis的xml映射文件路径
  mapper-locations: classpath:com/mapper/*.xml
  #配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.workmexh.domain
# spring配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379

    lettuce:
      pool:
        # 最大活跃连接数
        max-active: 8
        # 最大阻塞等待时间（负数表示无限制）
        max-wait: -1
        # 池中保持的最大空闲连接数
        max-idle: 8
        # 至少要保持的最小空闲连接数
        min-idle: 0

  mail:
    host: smtp.qq.com
    port: 587
    username: 1746186060@qq.com
    password: wpvyfmyjxvbodedf
    default-encoding: utf-8
  spring:
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/userdbspringbm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc:mysql://localhost:3306/userdbspringbm?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#      &serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
#    thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      suffix: .html
#      encoding: UTF-8
#      #数据源其他配置
#      initialSize: 5
#      minIdle: 5
#      maxActive: 20
#      maxWait: 60000
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,slf4j
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

